# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "The 13th ETSF Young Researchers' Meeting"
description: New frontiers in modeling electronic excited-states from confined systems to complex aggregates.<br>
   6-10/10/2016 Kings College London, London, UK

email:  yrm-info@kcl.ac.uk
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/blackboard.jpg"

name: 'YRM2016'
author: 'YRM2016'
author_image: "/assets/images/logo.png"

paginate:	3

url: "https://yrm2016.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
 # - icon: github
 #   desc: Test
 #   share_url: https://www.facebook.com/sharer.php
 #   share_title: ?t=
 #   share_link: "&amp;u="
#   - icon:	twitter
#     url:	https://twitter.com/dirkfabisch
#     desc: Follow me on twitter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

 - icon: facebook
   url:	https://www.facebook.com/YRM2016
   desc: Find us on facebook
   share_url: https://www.facebook.com/sharer.php
   share_title: ?t=
   share_link: "&amp;u="
 #
  # - icon:	github
  #   url:	https://github.com/yrm2016
  #   desc:	Fork me on github
  #   share_url: dsdsa
  #   share_title: dsadsa
  #   share_link: asddsa

 # - icon: mail
 #   url:	https://google.com/???
 #   desc:	Add me on google+
 #   share_url:
 #   share_title:
 #   share_link:
